WebsiteBanGiaySneaker/Models/SANPHAM.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanGiaySneaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
            this.CHITIETPNs = new HashSet<CHITIETPN>();
            this.CHITIETSPs = new HashSet<CHITIETSP>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string Anh { get; set; }
        public int MaNSX { get; set; }
        public Nullable<int> SoLuongTong { get; set; }
        public decimal DonGia { get; set; }
        public string Anh2 { get; set; }
        public string Anh3 { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPN> CHITIETPNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSP> CHITIETSPs { get; set; }
        public virtual NSX NSX { get; set; }
    }
}

WebsiteBanGiaySneaker/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanGiaySneaker.Models;

namespace WebsiteBanGiaySneaker.Controllers
{
    public class SanPhamController : Controller
    {
        WebsiteBanGiaySneakerEntities db = new WebsiteBanGiaySneakerEntities();
        // GET: SanPham

        public PartialViewResult SanPhamNoiBatPartial()
        {
            var listSPNoiBat = db.SANPHAMs.Take(5).ToList();
            return PartialView(listSPNoiBat);
        }

        public PartialViewResult DanhSachSanPhamPartial()
        {
            var listSP = db.SANPHAMs.Take(9).ToList();
            return PartialView(listSP);
        }

        //Xem chi tiết giày
        public ViewResult XemChiTiet(int masp = 0, int mansx = 0)
        {
            SANPHAM sp = db.SANPHAMs.SingleOrDefault(n => n.MaSP == masp);
            if (sp == null)
            {
                //Trả về trang báo lỗi
                Response.StatusCode = 404;
                return null;
            }
            //----
            var mau = from a in db.CHITIETSPs
                      join b in db.MauSacs
                      on a.MaMau equals b.MaMau
                      where (a.MaSP == masp)
                      select new
                      {
                          a.MaMau,
                          b.Color
                      };

            var size = from a in db.CHITIETSPs
                      join b in db.Sizes
                      on a.MaSize equals b.MaSize
                      where (a.MaSP== masp)
                      select new
                      {
                          a.MaSize,
                          b.Size1
                      };
            //---
            ViewBag.TenNSX = db.NSXes.Single(n => n.MaNSX == sp.MaNSX).TenNSX;
            ViewBag.MauSac = new SelectList(mau.GroupBy(g => g.MaMau).Select(g => g.FirstOrDefault()), "MaMau", "Color");
            ViewBag.Size = new SelectList(size.GroupBy(g => g.MaSize).Select(g => g.FirstOrDefault()), "MaSize", "Size1");
            //if (mau != null || size != null)
            //{
            //    TempData["trangthai"] = "Còn hàng";     
            //}
            //else
            //{
            //    TempData["trangthai"] = "Hết hàng";
            //}
            //Tạo list sản phẩm liên quan
            ViewBag.SPLienQuan = db.SANPHAMs.Where(n => n.MaSP != masp && n.MaNSX == mansx).Take(4).ToList();
            return View(sp);
        }

    }
}

WebsiteBanGiaySneaker/Views/SanPham/DanhSachSanPhamPartial.cshtml
@using WebsiteBanGiaySneaker.Models;
@*Định nghĩa kiểu dữ liệu cho model*@
@model  List<SANPHAM>

@foreach (var item in Model)
{
    <div class="col-md-4 product-men women_two">
        <div class="product-shoe-info shoe">
            <div class="men-pro-item">
                <div class="men-thumb-item">
                    <img width="200" height="200" src="@Url.Content("~/HinhAnh/HinhAnhSP/" + item.Anh)" alt="">
                    <div class="men-cart-pro">
                        <div class="inner-men-cart-pro">
                            <a href="@Url.Action("XemChiTiet", "SanPham", new { @masp = item.MaSP,@mansx = item.MaNSX })" class="link-product-add-cart">Xem nhanh</a>
                        </div>
                    </div>
                    @*<span class="product-new-top">New</span>*@
                </div>
                <div class="item-info-product">
                    @*Nếu tên sách dài quá 19 kí tự sẽ cắt tên sách ra lấy từ 0 đến kí tự 18*@
                    @if (item.TenSP.Length < 19)
                    {
                        <h4>
                            <a href="@Url.Action("XemChiTiet", "SanPham", new { @masp = item.MaSP,@mansx = item.MaNSX })">@item.TenSP</a>
                        </h4>
                    }
                    else
                    {
                        <h4>
                            <a title="@item.TenSP" href="@Url.Action("XemChiTiet", "SanPham", new { @masp = item.MaSP,@mansx = item.MaNSX })">@item.TenSP.Substring(0, 19)...</a>
                        </h4>
                    }
                    <div class="info-product-price">
                        <div class="grid_meta">
                            <div class="product_price">
                                <div class="grid-price ">
                                    <span class="money ">@string.Format("{0:0,0}", @item.DonGia) VNĐ</span>
                                </div>
                            </div>
                            @*<ul class="stars">
                                    <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
                                </ul>*@
                        </div>
                        @*<div class="shoe single-item hvr-outline-out">
                            @using (Html.BeginForm("ThemGioHang", "GioHang", new { @masp = item.MaSP, @URL = Request.Url.ToString() }))
                            {
                                <button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>
                            }
                        </div>*@
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
}

WebsiteBanGiaySneaker/Views/SanPham/SanPhamNoiBatPartial.cshtml
@using WebsiteBanGiaySneaker.Models;
@*Định nghĩa kiểu dữ liệu cho model*@
@model  List<SANPHAM>

@foreach (var item in Model)
{
    <a href="@Url.Action("XemChiTiet","SanPham",new { @masp = item.MaSP,@mansx = item.MaNSX})">
        <div class="special-sec1">
            <div class="col-xs-4 img-deals">
                <img src="@Url.Content("~/HinhAnh/HinhAnhSP/"+item.Anh)" alt="">
            </div>
            <div class="col-xs-8 img-deal1">
                <h3>@item.TenSP</h3>
                <p>@string.Format("{0:0,0}", @item.DonGia) VNĐ</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </a>
}

WebsiteBanGiaySneaker/Views/SanPham/XemChiTiet.cshtml
@using WebsiteBanGiaySneaker.Models;
@model SANPHAM

@{
    ViewBag.Title = "Chi tiết sản phẩm";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}


<!-- top Products -->
<div class="ads-grid_shop">
    <div class="shop_inner_inf">
        @if (TempData["kthanhcong"] != null)
        {
            <div class="alert alert-danger alert-dismissible" role="alert">
                <strong>@TempData["kthanhcong"]</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        @if (TempData["thanhcong"] != null)
        {
            <div class="alert alert-success alert-dismissible" role="alert">
                <strong>@TempData["thanhcong"]</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        @if (TempData["loisl"] != null)
        {
            <div class="alert alert-danger alert-dismissible" role="alert">
                <strong>@TempData["loisl"]</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <div class="col-md-4 single-right-left ">

            <div class="grid images_3_of_2">
                <div class="flexslider">

                    <ul class="slides">
                        <li data-thumb="@Url.Content("~/HinhAnh/HinhAnhSP/"+Model.Anh)">
                            <div class="thumb-image"> <img src="@Url.Content("~/HinhAnh/HinhAnhSP/"+Model.Anh)" data-imagezoom="true" class="img-responsive"> </div>
                        </li>
                        <li data-thumb="@Url.Content("~/HinhAnh/HinhAnhSP/"+Model.Anh2)">
                            <div class="thumb-image"> <img src="@Url.Content("~/HinhAnh/HinhAnhSP/"+Model.Anh2)" data-imagezoom="true" class="img-responsive"> </div>
                        </li>
                        <li data-thumb="@Url.Content("~/HinhAnh/HinhAnhSP/"+Model.Anh3)">
                            <div class="thumb-image"> <img src="@Url.Content("~/HinhAnh/HinhAnhSP/"+Model.Anh3)" data-imagezoom="true" class="img-responsive"> </div>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>

        @using (Html.BeginForm("ThemGioHang", "GioHang", new { @masp = Model.MaSP, @URL = Request.Url.ToString() }))
        {

            <div class="col-md-8 single-right-left simpleCart_shelfItem">
                <h3>@Model.TenSP</h3>
                <p>
                    <span class="item_price">Giá: @string.Format("{0:0,0}", Model.DonGia) VNĐ</span>
                    @*<del>$1,199</del>*@
                </p>

                <p>
                    <span class="item_price">Mã sản phẩm: @Model.MaSP</span>
                </p>

                <p>
                    <span class="item_price">Nhà sản xuất: @ViewBag.TenNSX</span>
                </p>

                <div class="color-quality">
                    <div class="color-quality-right">
                        <h5>Màu sắc:</h5>
                        @*@Html.DropDownList("MauSac", (IEnumerable<SelectListItem>)ViewBag.MauSac, new { @class = "form-control" })*@
                        @Html.DropDownList("MauSac")
                    </div>
                </div>
                <br />
                <div class="color-quality">
                    <div class="color-quality-right">
                        <h5>Size:</h5>
                        @*@Html.DropDownList("Size", (IEnumerable<SelectListItem>)ViewBag.Size, new { @class = "form-control" })*@
                        @Html.DropDownList("Size")
                    </div>
                </div>
                <br />

                <div class="occasion-cart">
                    <div class="shoe single-item single_page_b">
                        <input type="submit" name="submit" onclick="Validate()" value=" Thêm vào giỏ hàng" class="button add">
                    </div>
                </div>

            </div>
        }
        <div class="clearfix"> </div>
        <!-- /new_arrivals -->

        <div class="responsive_tabs">
            <div id="horizontalTab">
                <ul class="resp-tabs-list">
                    <li>Mô tả</li>
                    @*<li>Reviews</li>
                        <li>Information</li>*@
                </ul>
                <div class="resp-tabs-container">
                    <!--/tab_one-->
                    <div class="tab1">

                        <div class="single_page">
                            @*<h6>Lorem ipsum dolor sit amet</h6>*@
                            <p>
                                @Model.MoTa
                            </p>

                        </div>
                    </div>
                    <!--//tab_one-->

                </div>
            </div>
        </div>
        <!--//tabs-->
        <!-- /new_arrivals -->


        <div class="new_arrivals">
            <h3>Sản phẩm liên quan</h3>

            @foreach (var item in ViewBag.SPLienQuan)
            {
                <!-- /womens -->
                <div class="col-md-3 product-men women_two">
                    <div class="product-shoe-info shoe">
                        <div class="men-pro-item">
                            <div class="men-thumb-item">
                                <img width="200" height="200" src="@Url.Content("~/HinhAnh/HinhAnhSP/" + item.Anh)" alt="">
                                <div class="men-cart-pro">
                                    <div class="inner-men-cart-pro">
                                        <a href="@Url.Action("XemChiTiet", "SanPham", new { @masp = item.MaSP, @mansx = item.MaNSX })" class="link-product-add-cart">Xem nhanh</a>
                                    </div>
                                </div>
                                @*<span class="product-new-top">New</span>*@
                            </div>
                            <div class="item-info-product">
                                @*Nếu tên sách dài quá 19 kí tự sẽ cắt tên sách ra lấy từ 0 đến kí tự 18*@
                                @if (item.TenSP.Length < 19)
                                {
                                    <h4>
                                        <a href="@Url.Action("XemChiTiet", "SanPham", new { @masp = item.MaSP, @mansx = item.MaNSX })">@item.TenSP</a>
                                    </h4>
                                }
                                else
                                {
                                    <h4>
                                        <a title="@item.TenSP" href="@Url.Action("XemChiTiet", "SanPham", new { @masp = item.MaSP, @mansx = item.MaNSX })">@item.TenSP.Substring(0, 19)...</a>
                                    </h4>
                                }
                                <div class="info-product-price">
                                    <div class="grid_meta">
                                        <div class="product_price">
                                            <div class="grid-price ">
                                                <span class="money ">@string.Format("{0:0,0}", item.DonGia) VNĐ</span>
                                            </div>
                                        </div>
                                    </div>
                                    @*<div class="shoe single-item hvr-outline-out">
                                            <button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>
                                        </div>*@
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <!-- //womens -->
            }
            <div class="clearfix"></div>
        </div>
        <!--//new_arrivals-->


    </div>
</div>
<!-- //top products -->
<script type="text/javascript">
    function Validate() {
        var e = document.getElementById("MauSac");
        var f = document.getElementById("Size");
        var strS = f.options[f.selectedIndex].value;
        var strM = e.options[e.selectedIndex].value;

        if (strM == null || strM == "") {
            alert("Vui lòng chọn màu sắc");
        }
        if (strS == null || strS == "") {
            alert("Vui lòng chọn size");
        }
    }
</script>