WebsiteBanGiaySneaker/Areas/Admin/Controllers/QlyKhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanGiaySneaker.Models;
using PagedList;
using PagedList.Mvc;

namespace WebsiteBanGiaySneaker.Areas.Admin.Controllers
{
    public class QlyKhachHangController : BaseController
    {
        WebsiteBanGiaySneakerEntities db = new WebsiteBanGiaySneakerEntities();
        // GET: Admin/QlyKhachHang
        public ActionResult DanhSachKhachHang(string timkiem, int? page)
        {
            ViewBag.TuKhoa = timkiem;
            int pageNumber = (page ?? 1);
            int pageSize = 5;
            if (timkiem != null)
            {
                List<KHACHHANG> listKQ = db.KHACHHANGs.Where(n => n.TenKH.Contains(timkiem)).ToList();
                if (listKQ.Count == 0)
                {
                    TempData["thongbao"] = "Không tìm thấy khách hàng nào phù hợp.";
                    return View(db.KHACHHANGs.OrderBy(n => n.TenKH).ToPagedList(pageNumber, pageSize));
                }
                return View(listKQ.OrderBy(n => n.TenKH).ToPagedList(pageNumber, pageSize));
            }
            return View(db.KHACHHANGs.OrderBy(n => n.TenKH).ToPagedList(pageNumber, pageSize));
        }

        //Chi tiết
        public ActionResult HienThiKH(int makh)
        {
            //Lấy ra đối tượng sp theo mã
            KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.MAKH == makh);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(kh);
        }
    }
}

WebsiteBanGiaySneaker/Areas/Admin/Views/QlyKhachHang/DanhSachKhachHang.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<WebsiteBanGiaySneaker.Models.KHACHHANG>

@{
    /**/

    ViewBag.Title = "DanhSachKhachHang";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>KHÁCH HÀNG</h2>
<br />
@using (Html.BeginForm("DanhSachKhachHang", "QlyKhachHang", FormMethod.Get))
{
    <div class="col-lg-5">
        <div class="input-group custom-search-form">
            <input type="text" class="form-control" value="@ViewBag.TuKhoa" placeholder="Tìm kiếm theo tên" name="timkiem">
            <span class="input-group-btn">
                <button class="btn btn-success" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </span>
        </div>
    </div>
}
<br />
<hr />
@if (TempData["thongbao"] != null)
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <strong>@TempData["thongbao"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().MAKH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().TenKH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().DiaChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Sdt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MAKH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenKH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GioiTinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sdt)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |*@
                    @Html.ActionLink("Chi tiết", "HienThiKH", new { @makh = item.MAKH })
                    @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }
    </tbody>
</table>
@*Tạo link liên kết các trang*@
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
        <div>
            @Html.PagedListPager(Model, page => Url.Action("DanhSachKhachHang", new { @timkiem = @ViewBag.TuKhoa, page = page }))
        </div>
        <script>
            $(document).ready(function () {
                $('#dataTables-example').DataTable({
                    responsive: true
                });
            });
        </script>

WebsiteBanGiaySneaker/Areas/Admin/Views/QlyKhachHang/HienThiKH.cshtml
@model WebsiteBanGiaySneaker.Models.KHACHHANG

@{
    ViewBag.Title = "Chi tiết khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
<br/>
<h2>CHI TIẾT</h2>
<hr/>
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MAKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MAKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sdt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sdt)
        </dd>
    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    @Html.ActionLink("Trở về", "DanhSachKhachHang", null, new { @class = "btn btn-danger" })
</p>