WebsiteBanGiaySneaker/Controllers/CuaHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanGiaySneaker.Models;

namespace WebsiteBanGiaySneaker.Controllers
{
    public class CuaHangController : Controller
    {

        WebsiteBanGiaySneakerEntities db = new WebsiteBanGiaySneakerEntities();
        // GET: CuaHang
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FooterPartial()
        {
            return PartialView();
        }

        public ActionResult GioiThieu()
        {
            return View();
        }
       
    }
}

WebsiteBanGiaySneaker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebsiteBanGiaySneaker.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebsiteBanGiaySneaker/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}
<!-- banner -->
<div class="banner_top" id="home">
    <div class="wrapper_top_w3layouts">
        @Html.Partial("~/Views/Home/MenuPartial.cshtml")
        <!-- /slider -->
        <div class="slider">
            <div class="callbacks_container">
                <ul class="rslides callbacks callbacks1" id="slider4">

                    <li>
                        <div class="banner-top2">
                            <div class="banner-info-wthree">
                                <h3>Nike</h3>
                                <p>Những đôi giày hàng đầu.</p>

                            </div>

                        </div>
                    </li>
                    <li>
                        <div class="banner-top3">
                            <div class="banner-info-wthree">
                                <h3>Heels</h3>
                                <p>Phù hợp với tất cả mọi người.</p>

                            </div>

                        </div>
                    </li>
                    <li>
                        <div class="banner-top">
                            <div class="banner-info-wthree">
                                <h3>Sneakers</h3>
                                <p>Những đôi giày hàng đầu.</p>

                            </div>

                        </div>
                    </li>
                    <li>
                        <div class="banner-top1">
                            <div class="banner-info-wthree">
                                <h3>Adidas</h3>
                                <p>Phù hợp với tất cả mọi người.</p>

                            </div>

                        </div>
                    </li>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
        <!-- //slider -->
        <ul class="top_icons">
            <li><a href="#  "><span class="fa fa-facebook" aria-hidden="true"></span></a></li>
            <li><a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a></li>
            <li><a href="#"><span class="fa fa-linkedin" aria-hidden="true"></span></a></li>
            <li><a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a></li>

        </ul>
    </div>
</div>
<!-- //banner -->
<!-- /girds_bottom-->
<div class="grids_bottom">
    <div class="style-grids">
        <div class="col-md-6 style-grid style-grid-1">
            <img src="~/Content/NguoiDung/images/b1.jpg" alt="shoe">
        </div>
    </div>
    <div class="col-md-6 style-grid style-grid-2">
        <div class="style-image-1_info">
            <div class="style-grid-2-text_info">
                <h3>Nike DOWNSHIFTER</h3>
                <p>
                    Itaque earum rerum hic tenetur a sapiente delectus reiciendis maiores alias consequatur.sed quia non numquam eius modi
                    tempora incidunt ut labore et dolore .
                </p>
                <div class="shop-button">
                    @Html.ActionLink("Cửa hàng", "Index", "CuaHang", null, new { @class = "active" })
                </div>
            </div>
        </div>
        <div class="style-image-2">
            <img src="~/Content/NguoiDung/images/b2.jpg" alt="shoe">
            <div class="style-grid-2-text">
                <h3>Air force</h3>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
    </div>
<!-- //grids_bottom-->
<!-- /girds_bottom2-->
<div class="grids_sec_2">
    <div class="style-grids_main">
        <div class="col-md-6 grids_sec_2_left">
            <div class="grid_sec_info">
                <div class="style-grid-2-text_info">
                    <h3>Sneakers</h3>
                    <p>
                        Itaque earum rerum hic tenetur a sapiente delectus reiciendis maiores alias consequatur.sed quia non numquam eius modi
                        tempora incidunt ut labore .
                    </p>
                    <div class="shop-button">
                       @Html.ActionLink("Cửa hàng", "Index", "CuaHang", null, new { @class = "active" })
                    </div>
                </div>
            </div>
            <div class="style-image-2">
                <img src="~/Content/NguoiDung/images/b4.jpg" alt="shoe">
                <div class="style-grid-2-text">
                    <h3>Air force</h3>
                </div>
            </div>
        </div>
        <div class="col-md-6 grids_sec_2_left">

            <div class="style-image-2">
                <img src="~/Content/NguoiDung/images/b3.jpg" alt="shoe">
                <div class="style-grid-2-text">
                    <h3>Air force</h3>
                </div>
            </div>
            <div class="grid_sec_info last">
                <div class="style-grid-2-text_info">
                    <h3>Sneakers</h3>
                    <p>
                        Itaque earum rerum hic tenetur a sapiente delectus reiciendis maiores alias consequatur.sed quia non numquam eius modi
                        tempora incidunt ut labore .
                    </p>
                    <div class="shop-button two">
                       @Html.ActionLink("Cửa hàng", "Index", "CuaHang", null, new { @class = "active" })
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- //grids_bottom2-->
<!-- /Properties -->

WebsiteBanGiaySneaker/Views/Home/MenuPartial.cshtml
<div class="header_agileits">
    <div class="logo">
        <h1><a class="navbar-brand"><span>Yugo</span> <i>Shoes</i></a></h1>
    </div>
    <div class="overlay overlay-contentpush">
        <button type="button" class="overlay-close"><i class="fa fa-times" aria-hidden="true"></i></button>

        <nav>
            <ul>
                <li>@Html.ActionLink("Trang chủ", "Index", "Home", null, new { @class = "active" })</li>
                <li>@Html.ActionLink("Cửa hàng", "Index", "CuaHang", null, new { @class = "active" })</li>
                @if (Session["Userkh"] != null)
                {
                    <li>Xin chào @Session["Userkh"].ToString()</li>
                    <li>@Html.ActionLink("Đăng xuất", "DangXuat", "KhachHang", null, new { @class = "active" })</li>
                }
                else
                {
                    <li>@Html.ActionLink("Đăng nhập", "DangNhap", "KhachHang", null, new { @class = "active" })</li>
                    <li>@Html.ActionLink("Đăng ký", "DangKy", "KhachHang", null, new { @class = "active" })</li>
                }
                <li>@Html.ActionLink("Giới thiệu", "GioiThieu", "CuaHang", null, new { @class = "active" })</li>
            </ul>
        </nav>
    </div>
    <div class="mobile-nav-button">
        <button id="trigger-overlay" type="button"><i class="fa fa-bars" aria-hidden="true"></i></button>
    </div>
    <!-- cart details -->
    @*Chèn giỏi hàng partial*@
    @Html.Action("GioHangPartial", "GioHang")
    <!-- //cart details -->
    <!-- search -->
    <div class="search_w3ls_agileinfo">
        <div class="cd-main-header">
            <ul class="cd-header-buttons">
                <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
            </ul>
        </div>
        <div id="cd-search" class="cd-search">
            @using (Html.BeginForm("KQTimKiem", "TimKiem", FormMethod.Post))
            {
                <input name="txtTimKiem" type="search" placeholder="Nhập từ khóa cần tìm...">
            }
        </div>
    </div>
    <!-- //search -->
    <br />
    <div>@ViewBag.TenKH </div>

    <div class="clearfix"></div>
</div>